
export const NORMAL_CRITERIA = [
  'Normal',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Ice',
  'Fighting',
  'Poison',
  'Ground',
  'Flying',
  'Psychic',
  'Bug',
  'Rock',
  'Ghost',
  'Dragon',
  'Steel',
  'Fairy',
  'Dark',
  'Mega',
  'Legendary',
  'Mythical',
  'Ultra Beast',
  'Paradox',
  'Kanto',
  'Johto',
  'Hoenn',
  'Sinnoh',
  'Unova',
  'Kalos',
  'Alola',
  'Galar',
  'Paldea',
  'Has: Sturdy',
  'Can Evolve',
  'Final Evolution',
  'Partner Pokemon',
  'Knows: Brick Break',
  'Knows: Grass Knot',
  'Knows: Iron Tail',
  'Knows: Cut',
  'Knows: Flame Thrower',
  'Knows: Leer',
  'Knows: Mud Slap',
  'Has: Swift Swim',
  'Has: Cursed Body',
  'Has: Mold Breaker',
];


export const HARD_CRITERIA = [
  'Above 100 hp',
  'Above 100 sp atk',
  'Above 100 atk',
  'Above 100 sp def',
  'Above 100 def',
  'Above 100 speed',
  'Below 50 hp',
  'Below 50 sp atk',
  'Below 50 atk',
  'Below 50 sp def',
  'Below 50 def',
  'Below 50 speed',
  'Learns Grass Knot',
  'Learns Brick Break',
  'Learns Earthquake',
  'Learns Bind',
  'Learns Mud Slap',
  'Learns Close Combat',
  'Learns Dazzling Gleam',
  'Learns Dark Pulse',
  'Learns Heal Pulse',
  'Learns Scratch',
  'Learns Wish',
  'Learns Healing Wish',
  'Learns Belly Drum',
  'Learns After You',
  'Learns Sucker Punch',
  'Learns Cut',
  'Has: Drizzle',
  'Has: Sand Stream',
  'Has: Snow Warning',
  'Has: Grassy Surge',
  'Has: Magic Guard',
  'Has: Thick Fat',
  'Has: Flash Fire',
  'Has: Water Absorb',
  'Has: Sap Sipper',
  'Has: Prankster',
  'Has: Competitive',
  'Has: Frisk',
  'Has below 320 bst',
  'Has above 620 bst',
];
